window.HELLXBONE = {
  facebook: 'https://facebook.com/DIYOTHE',
  sumupShop: 'https://hellxbone.sumupstore.com/',
  products: [
    {
      id: 'boutique-hellxbone',
      title: 'Mes créations HELLXBONE',
      price: 'Prix et tailles sur SumUp',
      description: 'Découvre mes tee-shirts et mes autres créations dans ma boutique en ligne.',
      image: 'boutique-hellxbone.png',
      sumupUrl: 'https://hellxbone.sumupstore.com/'
    }
  ],
  articles: [
    {
        "id": "etats-generaux-metal-4-2026",
        "category": "Festival",
        "date": "2026-10-08",
        "title": "🤘🔥 LES ÉTATS GÉNÉRAUX DU METAL #4 — MONTPELLIER VA TREMBLER ! 💀",
        "excerpt": "10 et 11 octobre 2026 à Victoire 2 : concerts black, death, hardcore, post-punk, Puces Hell, Metal for Kids et infos PMR.",
        "body": [
            "🤘🔥 LES ÉTATS GÉNÉRAUX DU METAL #4 — MONTPELLIER VA TREMBLER ! 💀",
            "📅 10 & 11 OCTOBRE 2026",
            "📍 Victoire 2 — Saint-Jean-de-Védas (34)",
            "🎸 BLACK METAL • DEATH • HARDCORE • POST-PUNK",
            "🔥 DEUX JOURS POUR CÉLÉBRER NOTRE PUTAIN DE CULTURE METAL ! 🔥",
            "Ce week-end, direction Montpellier pour la quatrième édition des États GénéraUX du Metal, dans le cadre du festival EX TENEBRIS LUX ! 🤘",
            "Et attention, les amis : ici, il ne s'agit pas simplement de brancher quelques amplis et d'envoyer des décibels.",
            "On parle de rencontres, de découvertes, de concerts, de culture underground et surtout de cette formidable communauté qui fait vivre le metal ! 🖤",
            "💀 SAMEDI 10 OCTOBRE — PLACE AUX RIFFS !",
            "🎤 Dès 14h — ENTRÉE LIBRE",
            "🔥 Rencontres avec les professionnels du metal.",
            "🎨 Expositions autour de notre univers.",
            "🎸 Dès 18h, tremplin pour découvrir les groupes émergents.",
            "🍔 Foodtrucks et bar pour reprendre des forces !",
            "🔥 À PARTIR DE 19H30 — LA GROSSE ARTILLERIE !",
            "💀 THE GREAT OLD ONES 🇫🇷 — Du black metal atmosphérique, sombre et oppressant, inspiré de l'univers de Lovecraft. Une véritable plongée dans les ténèbres !",
            "💀 HEXIS 🇩🇰 — Du blackened hardcore brutal, du sludge et une atmosphère qui ne laisse aucun répit !",
            "💀 VIANDE 🇫🇷 — Du death metal obscur, viscéral et particulièrement malsain. Les amateurs de sonorités extrêmes vont être servis !",
            "🖤 VIOLENCE 🇩🇰 — Du post-punk moderne, sombre et hypnotique. Une touche différente dans cette soirée infernale !",
            "🎟️ Concerts payants : 23 € en prévente • 21 € tarif réduit • 25 € sur place.",
            "🤘 DIMANCHE 11 OCTOBRE — LE METAL EN FAMILLE !",
            "🕙 De 10h à 18h — ENTRÉE LIBRE",
            "☠️ LES PUCES HELL — Le paradis des collectionneurs et des passionnés !",
            "💿 Vinyles • 👕 Fringues et merchandising • 💀 Patchs et objets insolites • 📚 Livres et affiches • 🎸 Instruments et curiosités rock !",
            "🎱 14h — METAL BINGO",
            "Un bingo version metalleux ! De quoi passer un bon moment dans une ambiance complètement déjantée.",
            "🎸 16h — METAL FOR KIDS avec SMASH HIT COMBO & BOZO !",
            "Parce qu'il n'y a pas d'âge pour découvrir les riffs et apprendre à faire les cornes ! 🤘",
            "👶 Dès 5 ans • ⏱️ 45 minutes • 🎟️ 10 €",
            "♿ ACCESSIBILITÉ PMR — LE METAL, C'EST POUR TOUT LE MONDE ! 🖤",
            "Chez HELLXBONE, l'accessibilité des personnes handicapées est un sujet qui me tient particulièrement à cœur.",
            "Et bonne nouvelle : Victoire 2 annonce être conforme aux normes d'accessibilité pour les personnes à mobilité réduite et malvoyantes. 🤘",
            "✅ Salle annoncée accessible aux PMR.",
            "🅿️ Parking gratuit devant l'établissement.",
            "🍔 Bar et restauration disponibles pendant les concerts.",
            "⚠️ Attention : la salle précise qu'il n'y a pas de places assises dans sa configuration habituelle. L'existence d'un emplacement réservé aux fauteuils, les conditions d'accompagnement et l'accessibilité précise du patio ne sont pas détaillées.",
            "👉 Pour préparer votre venue, notamment en fauteuil roulant ou avec des difficultés à rester debout, contactez directement la salle.",
            "📞 04 67 47 91 00",
            "📧 info@victoire2.com",
            "Parce qu'un handicap ne devrait jamais empêcher de profiter d'un putain de bon concert ! ♿🤘",
            "📍 INFOS PRATIQUES",
            "🏴 VICTOIRE 2",
            "Domaine du Mas de Grille",
            "2 rue Théophraste Renaudot",
            "34430 Saint-Jean-de-Védas",
            "🎟️ Billetterie et programme :",
            "https://www.victoire2.com/saison_en_cours/ex-tenebris-lux-egm4/",
            "☠️ LE MOT HELLXBONE",
            "Deux jours de partage, de découvertes, de riffs et de passion.",
            "Des groupes confirmés, des talents émergents, des rencontres et une scène underground qui refuse de crever !",
            "Voilà exactement le genre d'événement qui mérite d'être soutenu et mis en lumière. 🖤",
            "Alors que tu sois fan de black, de death, de hardcore, collectionneur de vinyles ou simplement curieux de découvrir cet univers...",
            "🔥 FAIS TOURNER L'INFO ET SOUTIENS LA SCÈNE ! 🔥",
            "🤘 LONGUE VIE AUX ÉTATS GÉNÉRAUX DU METAL !",
            "💀 HELLXBONE",
            "L'art, le metal et la création contre la maladie et l'isolement.",
            "🖤 ROCK • METAL • UNDERGROUND"
        ]
    },
    {
      id: 'unexpected-calibrations-2026',
      category: 'Interview',
      date: '2026-10-07',
      title: '🔥🎸 INTERVIEW EXCLUSIVE — HELLXBONE × UNEXPECTED CALIBRATIONS 🎸🔥',
      excerpt: 'Unexpected Calibrations ouvre les portes de son univers post-djent : riffs lourds, atmosphères, émotions, Impermanence, clips et ambitions live.',
      body: [
        '🎤 HELLXBONE : Pour ceux qui découvrent Unexpected Calibrations aujourd’hui, comment présenteriez-vous le groupe, votre univers et votre identité musicale en quelques mots ?',
        '🎸 Unexpected Calibrations :',
        'Unexpected Calibrations est un groupe de post-djent originaire d’Ile de France. Notre musique cherche à créer un équilibre entre des riffs lourds et très rythmiques, des atmosphères plus aériennes et des passages mélodiques ou progressifs.',
        'Au-delà du style, nous cherchons surtout à construire un univers cohérent, aussi bien musicalement que visuellement. Nos morceaux parlent beaucoup de la condition humaine, de notre fragilité et de notre place face à quelque chose qui nous dépasse. L’idée est de faire ressentir quelque chose avant même de chercher à le définir.',
        'On insiste beaucoup sur l’aspect visuel dans notre communication et nos clips. Je recommande vraiment d’aller voir celui d’Albatross qui selon moi est d’un niveau énorme comparé à notre nombre d’années d’exercice.',
        '🎬 ALBATROSS — https://www.youtube.com/watch?v=Fy8xoiml02A&list=PLdh34pa4XA3s&index=2',
        '🎤 HELLXBONE : Votre musique navigue entre metal progressif, djent, passages atmosphériques et sonorités plus extrêmes. Quelles sont les influences qui ont le plus façonné votre son, et comment faites-vous pour garder une identité qui vous est propre ?',
        '🎸 Unexpected Calibrations :',
        'Nos influences sont assez larges. Elles vont du djent et du metal progressif aux sonorités plus extrêmes, mais aussi à des univers beaucoup plus atmosphériques et cinématographiques ou même dans le rap français et la trap ou la folk. On ne se met pas trop de limites de style. Si c’est lourd et qu’il y a des émotions, on garde.',
        'Pour l’identité, on essaie surtout de ne pas composer en fonction d’une étiquette. On part de ce que nous avons envie de faire entendre et de ressentir. Si un passage fonctionne avec un riff très lourd, on le garde. S’il doit laisser place à quelque chose de plus calme ou mélodique, on le fait. C’est probablement cette recherche de contraste qui finit par créer notre propre langage.',
        '🎤 HELLXBONE : Vos morceaux semblent accorder beaucoup d’importance aux ambiances, aux émotions et aux contrastes. Quand vous composez, est-ce que vous partez d’abord d’un riff, d’une atmosphère, d’un texte ou d’une idée précise que vous voulez transmettre ?',
        '🎸 Unexpected Calibrations :',
        'Il n’y a pas vraiment de recette unique. Un morceau peut partir d’un riff, d’une boucle, d’une ambiance ou simplement d’une idée.',
        'Mais nous essayons généralement d’avoir assez tôt une intention émotionnelle. Même si nous ne savons pas encore exactement où le morceau va nous emmener, nous savons ce que nous voulons qu’il fasse ressentir.',
        'Ensuite, la composition se construit autour de cette idée. Le texte et la musique doivent finir par raconter la même chose. Nous accordons aussi beaucoup d’importance aux silences, aux respirations et aux changements de dynamique. Pour nous, un morceau lourd n’est réellement lourd que s’il y a quelque chose avec quoi le mettre en contraste.',
        '🎬 SUFFOCATE — https://www.youtube.com/watch?v=nl83OIQXtbw&list=PLdh34pa4XA3s&index=3',
        '🎤 HELLXBONE : Votre EP Impermanence marque une étape importante pour Unexpected Calibrations. Qu’est-ce qu’il représente pour vous, et qu’est-ce que vous aimeriez que les auditeurs ressentent ou retiennent après l’avoir écouté ?',
        '🎸 Unexpected Calibrations :',
        'Impermanence représente avant tout le premier véritable témoignage de ce qu’est Unexpected Calibrations.',
        'C’est une étape importante parce qu’il nous permet enfin de réunir plusieurs morceaux dans un même univers et de montrer la direction que nous voulons prendre. Le titre de l’EP n’est d’ailleurs pas anodin : l’impermanence, c’est cette idée que tout est temporaire, que nous sommes nous-mêmes de passage et que tout ce que nous construisons finit par évoluer ou disparaître.',
        'C’est aussi quelque chose que nous ressentons dans notre propre parcours de groupe.',
        'Depuis sa création, Unexpected Calibrations a beaucoup évolué, et l’EP est une photographie de cette période.',
        'Nous ne cherchons pas forcément à ce que les gens ressortent avec un message précis. Si quelqu’un termine l’écoute avec une émotion, une image, une question ou simplement l’envie de réécouter l’EP, alors nous avons déjà réussi quelque chose.',
        'Il sortira le 23 octobre 2026.',
        '🎤 HELLXBONE : Pour finir, quels sont les prochains objectifs d’Unexpected Calibrations : nouveaux morceaux, concerts, clips, album, tournée ? Et si quelqu’un ne devait écouter qu’un seul titre pour découvrir le groupe, lequel choisiriez-vous ?',
        '🎸 Unexpected Calibrations :',
        'Nous avons 2 priorités à ce jour, la première aujourd’hui, c’est clairement composer de nouveaux morceaux pour pouvoir proposer des lives plus complets et plus variés.',
        'La seconde est le live. Nous voulons continuer à faire des concerts, améliorer notre prestation et développer notre mise en scène pour donner à notre musique une véritable dimension scénique et aussi sortir de notre région parisienne et rencontrer le public des autres régions.',
        'Nous travaillons également sur de nouveaux morceaux et sur plusieurs contenus vidéo. Le clip d’« Insignificance » arrivera le 18 septembre et marquera une nouvelle étape dans l’évolution du groupe. Le second EP est en composition et nous jouons déjà en live un morceau inédit dont la date de diffusion n’est pas encore définie.',
        'Pour découvrir Unexpected Calibrations, nous choisirions « Albatross ». C’est un morceau qui représente particulièrement bien la direction que nous voulons prendre : des riffs lourds et très rythmiques, des passages atmosphériques, de la tension et une vraie volonté de créer un voyage plutôt que simplement enchaîner les parties.',
        '💀🔥 LE MOT DE LA FIN — HELLXBONE',
        'Un énorme merci à Unexpected Calibrations d’avoir pris le temps de répondre à cette interview et de nous ouvrir les portes de leur univers.',
        'Entre puissance, atmosphères, émotions et contrastes, le groupe développe une identité qui mérite clairement qu’on tende l’oreille.',
        'HELLXBONE continuera de mettre en avant ceux qui font vivre la scène Metal, Rock et Underground.',
        'À vous maintenant de pousser le son et de découvrir Unexpected Calibrations.',
        '🤘 HELLXBONE'
      ]
    },
    {
      id: 'mauges-pit-fest-v-2026',
      category: 'Festival',
      date: '2026-10-06',
      title: '🤘🔥 MAUGES PIT FEST V — LE METAL DES MAUGES A ENCORE FRAPPÉ FORT ! 🔥🤘',
      excerpt: 'Deux jours de riffs, 13 groupes, une ambiance énorme et surtout une accessibilité PMR formidable : longue vie au Mauges Pit Fest ! 🤘💀',
      body: [
        'Il y a des festivals où l’on vient simplement voir des groupes. Et puis il y a ceux où l’on se sent immédiatement à la maison. 💀❤️',
        'Le Mauges Pit Fest, les 2 et 3 octobre 2026 à Saint-Macaire-en-Mauges, fait clairement partie de cette deuxième catégorie. Pour cette cinquième édition, la salle Thomas-Dupouet a une nouvelle fois tremblé sous les riffs, les pogos, les décibels et cette putain de bonne ambiance qui fait tout le charme du metal. 🤘🔥',
        'Cette année, le festival proposait 13 groupes pour environ 11 heures de musique, avec une affiche allant du modern metal au stoner, du hardcore au hard-rock, en passant par le melodeath, le punk et le thrash.',
        '🎸 UNE AFFICHE QUI SENTAIT BON LE RIFF ET LA SUEUR',
        'Parmi les formations présentes cette année, on retrouvait notamment :',
        '🔥 REVNOIR — modern metal sombre, massif et moderne.',
        '🌌 MARS RED SKY — stoner lourd, psychédélique et planant.',
        '💀 DESTINITY — du melodeath qui ne vient clairement pas distribuer des fleurs.',
        '⚡ BUKOWSKI — du hard-rock qui sent l’ampli chauffé à blanc.',
        '👊 WAKE THE DEAD — hardcore : énergie brute et cervicales en danger.',
        '🔥 ARCANIA — du thrash metal mélodique qui défend fièrement les couleurs locales.',
        '🧨 ACID GRAS — garage punk, crade juste comme il faut et terriblement efficace.',
        'Et bien d’autres groupes venaient compléter cette affiche, avec une vraie diversité dans les styles.',
        'Mais le Mauges Pit Fest, ce n’est pas simplement une succession de concerts.',
        'C’est une ambiance.',
        'C’est le mec que tu ne connais pas qui te parle comme si vous aviez déjà fait dix festivals ensemble. 🍻',
        'C’est le sourire des bénévoles.',
        'C’est le public qui se mélange.',
        'Ce sont les vestes à patches, les cheveux longs, les crânes rasés, les familles, les anciens, les jeunes… et cette communauté metal qui sait encore ce que signifie le mot fraternité. 🤘❤️',
        '♿🤘 UNE ACCESSIBILITÉ PMR QUI MÉRITE UN ÉNORME RESPECT',
        'Et là, je veux vraiment insister.',
        'En étant moi-même en situation de handicap, je sais très bien qu’aller à un festival peut parfois devenir une véritable expédition.',
        'Au Mauges Pit Fest, j’ai vécu exactement l’inverse.',
        '💚 Dès le parking, j’ai été super bien accueilli.',
        '💚 Au passage des bracelets, même chose.',
        '💚 Les bénévoles étaient disponibles et avenants.',
        '💚 Et même les festivaliers avaient cette attention naturelle qui fait énormément de bien.',
        'Je suis arrivé pour profiter du metal, pas pour passer ma soirée à me demander comment j’allais réussir à me déplacer ou à accéder à quelque chose.',
        'Et ça, bordel… ça change tout.',
        'Permettre aux personnes en situation de handicap de vivre un festival comme tout le monde, de profiter des concerts, de l’ambiance, des rencontres et des décibels, ce n’est pas un petit détail logistique.',
        'C’est essentiel. ♿❤️🤘',
        'Alors pour ça :',
        'MERCI. VRAIMENT.',
        '🍔🍺 UN FESTIVAL QUI NE SE LIMITE PAS À LA SCÈNE',
        'Le festival proposait également tout ce qu’il fallait autour des concerts pour profiter pleinement de l’événement : restauration, bar, merchandising, exposants et toute cette ambiance qui permet de rester plongé dans l’univers metal pendant des heures.',
        'Bref : tu viens pour les riffs… et tu peux rester tranquillement dans ton univers metal. 😈',
        '🖤 LONGUE VIE AU MAUGES PIT FEST',
        'Ce genre de festival doit vivre.',
        'Parce que derrière les amplis, les lumières et les groupes, il y a surtout des bénévoles, une organisation et des passionnés qui se bougent le cul pour faire vivre la scène metal.',
        'Et ça mérite du respect. 🤘',
        'Le Mauges Pit Fest prouve qu’il n’est pas nécessaire d’avoir 60 000 personnes devant une scène pour ressentir quelque chose de puissant.',
        'Parfois, une salle pleine de passionnés, quelques amplis poussés dans le rouge et une équipe qui accueille les gens avec le sourire suffisent largement.',
        '🔥 Du metal.',
        '🔥 Des rencontres.',
        '🔥 Une putain de bonne ambiance.',
        '🔥 Une accessibilité PMR formidable.',
        '🔥 Et surtout une véritable âme.',
        'Je suis venu.',
        'J’ai profité.',
        'J’ai pris ma dose de riffs.',
        'Et je reviendrai. 🤘💀',
        'LONGUE VIE AU MAUGES PIT FEST !',
        'LONGUE VIE AUX BÉNÉVOLES !',
        'LONGUE VIE AUX GROUPES !',
        'ET LONGUE VIE AU METAL DANS LES MAUGES ! 🔥🔥🔥',
        '🤘💀 HELLXBONE 💀🤘'
      ]
    },
    {
      id: 'interview-crorif-2026',
      category: 'Interview',
      date: '2026-10-06',
      title: '🔥🎸 INTERVIEW EXCLUSIVE — HELLXBONE × CRORIF 🎸🔥',
      excerpt: 'Bienvenue dans l’univers complètement barré de CRORIF : du riff, de l’autodérision, des solos, du WTF et surtout une sacrée dose de bordel sur scène. 🤘',
      imageBottom: 'crorif-portrait.webp',
      imageBottomAlt: 'CRORIF — portrait rock dans une ambiance sombre et enfumée',
      body: [
        '💀 Bienvenue dans l’univers complètement barré de CRORIF ! Du riff, de l’autodérision, des solos, du WTF et surtout une sacrée dose de bordel sur scène. 🤘',
        '🎤 HELLXBONE : Pour ceux qui tombent sur CRORIF pour la première fois, présentez-nous le groupe. Qui se cache derrière CRORIF, comment le projet est-il né et surtout… d’où vient ce foutu nom ?',
        '🎸 CRORIF : « Un "groupe" ? Non, juste un mec tout seul. Pour le nom, c\'est simple : je fais des "crorif de guitare" — à prononcer impérativement avec une voix de débile. 😆 L\'histoire ? Ma chanteuse m\'a planté en pleine tournée. Panique. J\'ai composé 30 minutes de son et j\'ai créé des voix pour me meubler. La mienne, pitchée très grave, c\'est le guitariste virtuose insupportable qui se la raconte. Et les voix aiguës ("Petit Bout"), ce sont les voix cyniques qui passent leur temps à se foutre de sa gueule et à chauffer le public pour qu\'il le hue. Un vrai dialogue de sourds. » 🤘',
        '🔥 HELLXBONE : On vous présente comme du “rock WTF et festif”, avec des riffs tranchants, des solos qui sentent bon les années 90 et pas mal de second degré. Mais musicalement, quelles sont les influences qui ont réellement construit CRORIF ?',
        '🎸 CRORIF : « Un crash entre Stupeflip et Ultra Vomit. 💥 Stupeflip pour le côté électro déjanté et les voix, Ultra Vomit pour les gros riffs. La seule différence, c\'est qu\'eux ont du talent, alors que moi j\'ai juste une pédale d\'effet et beaucoup d\'illusions. » 😂🤘',
        '🤘 HELLXBONE : Chez vous, le concert semble presque aussi important que les morceaux eux-mêmes. Votre public est régulièrement embarqué dans le show, jusqu’à parfois devenir une partie du spectacle. Quand vous montez sur scène, qu’est-ce qui est préparé et quelle place laissez-vous au bordel total et à l’improvisation ?',
        '🎤 CRORIF : « Dans la vie je suis hôtelier, je parle à des centaines d\'inconnus par jour : le contact est naturel. J\'ai aussi mes pièges — comme faire crier "A-E-R-O-BEAT" au public jusqu\'à ce qu\'ils comprennent —, mais le reste c\'est du feeling. On est là pour rigoler… et afficher le premier rang, c\'est du bonus. » 😈🔥',
        '🎶 HELLXBONE : Vous avez enchaîné plusieurs scènes en 2026, de petits lieux rock parisiens jusqu’au Skybird Fest devant un public beaucoup plus large et très différent. Est-ce que jouer devant des publics aussi variés change votre manière d’aborder un concert, ou CRORIF débarque partout avec exactement la même mission : retourner la salle ?',
        '🎸 CRORIF : « En petite salle, la proximité est géniale : je peux regarder les gens dans les yeux quand je leur fais croire que je suis une légende du rock. 😎 En festival outdoor comme le Skybird, c\'est autre chose : il faut que mon ego traverse 50 mètres de champ. Donc j\'occupe tout l\'espace, je prends des poses de Guitar Hero XXL 🎸 et je fais comme si les 2 000 personnes étaient là uniquement pour aduler mes solos. » 🤘🔥',
        '🚀 HELLXBONE : Maintenant, parlons de la suite. Nouveaux morceaux, enregistrements, clips, concerts, festivals… qu’est-ce qui se prépare actuellement dans les entrailles de CRORIF, et jusqu’où vous aimeriez pousser ce projet ?',
        '🎤 CRORIF : « Objectif principal : faire assez de dates et de festivals pour enfin rembourser mon matos de rockstar — mon mur de Marshall et mes 12 guitares. 😂🎸 Et accessoirement, continuer de poster du contenu live sur YouTube pour prouver à ma banque que c\'est un vrai projet. »',
        '📺 YouTube : https://m.youtube.com/@CRORIF',
        '💀🔥 LE MOT DE LA FIN — HELLXBONE',
        '🎤 HELLXBONE : Je vous laisse carte blanche… le dernier mot est à CRORIF.',
        '🎸 CRORIF : « Bougez-vous pour soutenir votre scène locale ! 🤘 J\'ai 40 piges : dans dix ans je suis trop vieux, j\'aurai de l\'arthrose dans les doigts et je serai réduit à jouer à la pétanque. 😂 D\'ici là, j\'offre mon album pour un temps limité sur : 👉 https://crorif.carrd.co/ …tant que je tiens encore debout ! » 🤘🔥',
        '🖤 Merci à CRORIF d’avoir pris le temps de répondre à HELLXBONE. Continue à foutre du riff 🎸, de l’énergie 🔥 et du joyeux bordel 🤘 sur les scènes !',
        '💀 Fred — HELLXBONE / DiyOthe'
      ]
    },
    {
      id: 'war-metal-fest-2026',
      category: 'Festival',
      date: '2026-10-05',
      title: 'WAR METAL FEST III : Épernay a pris une sacrée claque ! 🤘🔥',
      excerpt: 'Huit groupes, du heavy au deathcore, une ambiance de fosse et une organisation aux petits oignons : le WAR METAL FEST III a encore prouvé que le metal français sait foutre le feu.',
      body: [
        'Le WAR METAL FEST III, c’était le 26 septembre 2026 à Épernay, et bordel, quelle journée ! Huit groupes sur scène, des styles différents, des riffs à la chaîne et cette ambiance qu’on aime : du bruit, de la sueur, des passionnés et zéro chichi.',
        'Sentence Hill a ouvert les hostilités avec son mélange groove, thrash et metalcore. Prime Fire a ensuite ramené un heavy metal bien solide, direct et sans fioritures. Ares a défendu les racines du heavy avec efficacité, avant que Derelicts ne plonge la salle dans un death metal progressif plus moderne et travaillé.',
        'Puis Protogonos a fait monter la pression avec une énergie énorme et un metalcore taillé pour la scène. Rankken a enchaîné avec son thrash/death précis, lourd et tranchant : du riff, du groove et une vraie présence scénique.',
        'LocoMuerte a ensuite retourné la fosse avec son crossover chicano ultra-fédérateur. Impossible de rester planté comme un piquet quand la machine démarre. Et pour terminer, DeathAwaits a envoyé son deathcore moderne, massif et sans concession.',
        'Au final, cette troisième édition du WAR METAL FEST a montré ce qu’un festival metal indépendant peut faire de mieux : une vraie diversité de groupes, une organisation carrée, de la restauration, des stands, des bénévoles investis et surtout une putain d’ambiance.',
        'Sentence Hill, Prime Fire, Ares, Derelicts, Protogonos, Rankken, LocoMuerte et DeathAwaits : huit groupes, huit univers, mais une seule religion ce jour-là — LE METAL.',
        'Respect au WAR METAL FEST et à toute l’équipe qui fait vivre ce rendez-vous. Ce genre de festival, c’est exactement ce qu’il faut soutenir : du local, du lourd, du passionné et une scène qui ne demande qu’à rugir encore plus fort.',
        'MAKE METAL, NOT WAR. 🤘🔥'
      ]
    },
{
  "id": "reouverture-boutique-2026",
  "category": "Actualités",
  "date": "2026-10-03",
  "title": "La boutique HELLXBONE est de retour ! 🤘",
  "excerpt": "Après un petit ménage de printemps, je rouvre les portes de ma boutique en ligne. Les créations HELLXBONE reprennent du service !",
  "image": "boutique-hellxbone.png",
  "imageAlt": "Tee-shirt blanc HELLXBONE présenté de dos sur un mannequin noir dans une boutique rock et metal",
  "shopUrl": "https://hellxbone.sumupstore.com/",
  "body": [
    "La boutique HELLXBONE est de nouveau ouverte ! Après un petit ménage de printemps, j’ai remis de l’ordre pour te faire retrouver mes créations dans ma boutique en ligne.",
    "Du rock, du metal et des visuels qui ont du caractère : je crée chaque dessin moi-même, avec l’envie de faire vivre mon univers sur tes tee-shirts.",
    "Derrière HELLXBONE, il y a aussi ma démarche avec l’association DIYOTHE : combattre la maladie et l’isolement social grâce à la création artistique.",
    "Viens faire un tour dans la boutique et partage la nouvelle autour de toi. Merci pour ton soutien, ça m’aide à continuer à créer ! 🤘"
  ]
},
    {
      id: 'bienvenue',
      category: 'Actualités',
      date: '2026-10-03',
      title: 'Bienvenue dans HELLXBONE',
      excerpt: 'Art, rock, metal et créations indépendantes : bienvenue dans mon univers.',
      body: [
        'Bienvenue dans HELLXBONE, mon univers artistique rock, metal et underground.',
        'À travers mon association DIYOTHE, je lutte contre la maladie et l’isolement social grâce à mes créations artistiques.',
        'Retrouve mes nouveautés sur Facebook : https://facebook.com/DIYOTHE',
        'Découvre mes créations dans ma boutique : https://hellxbone.sumupstore.com/'
      ]
    }
  ]
};


