(() => {
  const KEY='hellxbone-skulls-v1';
  const names=['Punk','Vampire','Biker','Démon','Pirate','Goth','Thrash','Sorcière','Motörcrâne','Faucheur','Zombie','Black metal','Rockeur','Nosferatu','Roadie','Cerbère','Corsaire','Reine noire','Anarchiste','Dracula','Hellrider','Infernal','Capitaine','Lune noire','Chaos','Immortel','Acier','Lucifer','Fantôme','Éclipse'];
  const skulls=names.map((name,id)=>({id,name,art:id%6,rarity:id>=24?'Légendaire':id>=12?'Rare':'Classique'}));
  let state={owned:[],bones:0,lastDay:'',memoryDay:'',lastSkull:null}, storageOK=true, selected=null, memory=null, message='';
  const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Europe/Paris',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
  try {const saved=JSON.parse(localStorage.getItem(KEY)||'null');if(saved&&Array.isArray(saved.owned)){state={...state,...saved,owned:[...new Set(saved.owned.filter(x=>Number.isInteger(x)&&x>=0&&x<30))],bones:Math.max(0,Number(saved.bones)||0)};}localStorage.setItem(KEY,JSON.stringify(state));}catch(e){storageOK=false;}
  const save=()=>{try{localStorage.setItem(KEY,JSON.stringify(state));return true;}catch(e){storageOK=false;return false;}};
  const rand=n=>{const a=new Uint32Array(1);crypto.getRandomValues(a);return Math.floor(a[0]/4294967296*n);};
  const art=(s,locked=false)=>`<div class="skull-art art-${s.art}${locked?' locked':''}" role="img" aria-label="${locked?'Crâne à découvrir':s.name}"></div>`;
  const card=s=>`<div class="skull-card ${state.owned.includes(s.id)?'owned':'undiscovered'} ${s.rarity==='Légendaire'?'legendary':''}">${art(s,!state.owned.includes(s.id))}<strong>${state.owned.includes(s.id)?s.name:'???'}</strong><small>${s.rarity}</small></div>`;
  function draw(){
    const root=document.getElementById('skull-game');if(!root)return;
    const used=state.lastDay===today();const recent=skulls[state.lastSkull];
    root.innerHTML=`<section class="game-hero"><span class="pill">Une collection 100 % metal</span><h2>☠ Le Crâne du jour</h2><p>Choisis un cercueil. Découvre ton crâne.</p><div class="bone-count">🦴 ${state.bones} os · ${state.owned.length}/30 crânes</div><div class="coffins">${[0,1,2].map(i=>`<button class="coffin coffin-${i} ${selected===i?'selected':''}" data-coffin="${i}" aria-label="Choisir le cercueil ${i+1}" aria-pressed="${selected===i}" ${used||!storageOK?'disabled':''}><span>Cercueil ${i+1}</span></button>`).join('')}</div><button class="button open-coffin" data-game="open" ${used||selected===null||!storageOK?'disabled':''}>${used?'Déjà ouvert aujourd’hui':'Ouvrir mon cercueil'}</button><p class="game-note">${used?'Reviens demain pour un nouveau crâne.':'1 ouverture gratuite par jour · changement à minuit, heure de Paris.'}</p><p class="game-message" role="status" aria-live="polite">${message}</p>${used&&recent?`<div class="daily-result">${art(recent)}<h3>${recent.name}</h3><span class="pill">${recent.rarity}</span><p>Ta découverte du jour</p><button class="button secondary" data-game="share">Partager ma trouvaille 🤘</button></div>`:''}</section><section><h2 class="section-title">Ma collection <small>${state.owned.length}/30</small></h2><p>Un doublon rapporte 1 os. Avec 5 os, débloque un crâne manquant.</p><button class="button secondary" data-game="unlock" ${state.bones<5||state.owned.length===30||!storageOK?'disabled':''}>${state.owned.length===30?'Collection complète 🤘':'Échanger 5 os'}</button><div class="skull-collection">${skulls.map(card).join('')}</div></section><section class="memory-section"><h2>Défi mémoire</h2><p>Trouve les 6 paires en 20 secondes. Gagne 1 os, une fois par jour. Tu peux aussi jouer sans chrono pour t’entraîner.</p><button class="button" data-game="memory" ${memory?.active?'disabled':''}>Défi 20 secondes</button> <button class="button secondary" data-game="practice" ${memory?.active?'disabled':''}>Sans chrono</button><p class="game-note">${state.memoryDay===today()?'Os du défi déjà gagné aujourd’hui.':'1 os à gagner aujourd’hui.'}</p><div id="memory-board"></div></section><details class="game-rules"><summary>Comment ça marche ?</summary><p>Tout est gratuit. Les os et les crânes sont des objets virtuels, sans valeur monétaire. Tous les cercueils offrent les mêmes chances : 65 % classique, 28 % rare, 7 % légendaire. L’échange de 5 os garantit un crâne manquant.</p><p>La collection reste dans ce navigateur, sur cet appareil. Effacer ses données peut effacer ta progression. Aucune connexion n’est nécessaire.</p></details>${!storageOK?'<p role="alert">La sauvegarde est indisponible dans ce navigateur. Autorise le stockage local pour ouvrir ton cercueil et conserver ta collection.</p>':''}`;
    drawMemory();
  }
  function drawMemory(){const board=document.getElementById('memory-board');if(!board||!memory)return;board.innerHTML=`<p role="status">${memory.practice?'Entraînement sans chrono':`Temps : <strong id="memory-time">${Math.max(0,Math.ceil((memory.deadline-Date.now())/1000))}</strong> s`} · ${memory.matched.length/2}/6 paires</p><div class="memory-grid">${memory.cards.map((s,i)=>{const face=memory.flipped.includes(i)||memory.matched.includes(i);return `<button class="memory-card ${face?'face-up':''}" data-memory="${i}" aria-label="${face?s.name:'Carte cachée '+(i+1)}" ${!memory.active||face?'disabled':''}>${face?art(s):'<span>☠</span>'}</button>`;}).join('')}</div><p role="status" aria-live="polite">${memory.result||''}</p>`;}
  function finishMemory(won){memory.active=false;clearInterval(memory.timer);if(won){if(!memory.practice&&state.memoryDay!==today()&&storageOK){state.bones++;state.memoryDay=today();save();memory.result='Les 6 paires trouvées ! +1 os 🤘';}else memory.result='Les 6 paires trouvées ! Bien joué 🤘';}else memory.result='Temps écoulé ! Réessaie ou entraîne-toi sans chrono.';draw();}
  function startMemory(practice){if(memory?.active)return;const cards=[...skulls.slice(0,6),...skulls.slice(0,6)];for(let i=cards.length-1;i>0;i--){const j=rand(i+1);[cards[i],cards[j]]=[cards[j],cards[i]];}memory={cards,flipped:[],matched:[],active:true,locked:false,practice,deadline:Date.now()+20000,result:''};drawMemory();if(!practice)memory.timer=setInterval(()=>{if(!memory.active)return;const left=Math.max(0,Math.ceil((memory.deadline-Date.now())/1000));const el=document.getElementById('memory-time');if(el)el.textContent=left;if(left===0)finishMemory(false);},200);}
  function flip(i){const m=memory;if(!m?.active||m.locked||m.flipped.includes(i)||m.matched.includes(i))return;if(!m.practice&&Date.now()>=m.deadline){finishMemory(false);return;}m.flipped.push(i);drawMemory();if(m.flipped.length===2){const [a,b]=m.flipped;if(m.cards[a].id===m.cards[b].id){m.matched.push(a,b);m.flipped=[];if(m.matched.length===12)finishMemory(true);else drawMemory();}else{m.locked=true;setTimeout(()=>{if(memory!==m||!m.active)return;m.flipped=[];m.locked=false;drawMemory();},650);}}}
  async function action(kind){
    if(kind==='open'){if(!storageOK||state.lastDay===today()||selected===null)return;const roll=rand(100);const pool=roll<65?skulls.slice(0,12):roll<93?skulls.slice(12,24):skulls.slice(24);const s=pool[rand(pool.length)];const duplicate=state.owned.includes(s.id);if(duplicate)state.bones++;else state.owned.push(s.id);state.lastDay=today();state.lastSkull=s.id;message=duplicate?`${s.name} : un doublon, +1 os !`:`Nouveau crâne : ${s.name} ! 🤘`;save();draw();}
    if(kind==='unlock'){if(!storageOK||state.bones<5)return;const missing=skulls.filter(s=>!state.owned.includes(s.id));if(!missing.length)return;const s=missing[rand(missing.length)];state.bones-=5;state.owned.push(s.id);message=`${s.name} rejoint ta collection !`;save();draw();}
    if(kind==='memory'||kind==='practice')startMemory(kind==='practice');
    if(kind==='share'){const s=skulls[state.lastSkull];if(!s)return;const text=`☠ J’ai découvert ${s.name} (${s.rarity}) dans Le Crâne du jour HELLXBONE ! 🤘`;try{if(navigator.share)await navigator.share({title:'Le Crâne du jour — HELLXBONE',text,url:location.href.split('#')[0]+'#jeu'});else if(navigator.clipboard){await navigator.clipboard.writeText(text+' '+location.href.split('#')[0]+'#jeu');message='Lien copié : partage-le avec tes potes !';draw();}else{message=text;draw();}}catch(e){if(e.name!=='AbortError'){message='Le partage est indisponible. Partage le lien de l’application.';draw();}}}
  }
  document.addEventListener('click',e=>{const el=e.target.closest('[data-coffin],[data-game],[data-memory]');if(!el)return;if(el.dataset.coffin!==undefined){if(state.lastDay===today())return;selected=Number(el.dataset.coffin);draw();}else if(el.dataset.memory!==undefined)flip(Number(el.dataset.memory));else action(el.dataset.game);});
  window.HellGame={render(){app.innerHTML='<div id="skull-game"></div>';draw();},stop(){if(memory?.active){memory.active=false;clearInterval(memory.timer);memory.result='Partie interrompue. Relance un défi quand tu veux.';}}};
})();
