(()=>{const ROWS=7,COLS=7,BASE_MOVES=30,ICONS=['💀','🎸','🔥','🤘','⚡','☠️'],LEVEL_GOALS=[600,1400,2600,4200,6500,9000,12000];let board=[],score=0,moves=BASE_MOVES,combo=0,level=1,selected=null,busy=false,pointerStart=null,audio=null,master=null,audioReady=false,best=Number(localStorage.getItem('hellx-riff-best')||0),globalLevel=Number(localStorage.getItem('hellx-riff-global-level')||1),badMoves=0,lastBadAt=0,extraAwarded=new Set();
const q=s=>document.querySelector(s),pos=i=>[Math.floor(i/COLS),i%COLS],idx=(r,c)=>r*COLS+c,wait=ms=>new Promise(r=>setTimeout(r,ms));
let muted=false;localStorage.setItem('hellx-riff-muted','0');
function initAudioNow(){try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return false;if(!audio){audio=new AC();master=audio.createGain();master.gain.value=1.35;master.connect(audio.destination)}if(audio.state==='suspended')audio.resume();audioReady=audio.state==='running'||audio.state==='suspended';return audioReady}catch(e){return false}}
function unlockAudio(){initAudioNow();if(audio&&audio.state==='suspended')audio.resume().catch(()=>{});if(audio){try{const o=audio.createOscillator(),g=audio.createGain();g.gain.value=.00001;o.connect(g);g.connect(master||audio.destination);o.start();o.stop(audio.currentTime+.01)}catch(e){}}}
['pointerdown','touchstart','click'].forEach(ev=>document.addEventListener(ev,unlockAudio,{capture:true,passive:true,once:true}));
function tone(freq,dur=.08,type='square',vol=.05,delay=0,slide=0){if(muted)return;if(!initAudioNow()||!audio)return;try{const t=audio.currentTime+delay,o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,t);if(slide)o.frequency.exponentialRampToValueAtTime(Math.max(30,freq+slide),t+dur);g.gain.setValueAtTime(.0001,t);g.gain.exponentialRampToValueAtTime(vol,t+.006);g.gain.exponentialRampToValueAtTime(.0001,t+dur);o.connect(g);g.connect(master||audio.destination);o.start(t);o.stop(t+dur+.03)}catch(e){}}
function noise(dur=.09,vol=.025){if(muted||!initAudioNow()||!audio)return;try{const n=Math.max(1,Math.floor(audio.sampleRate*dur)),buf=audio.createBuffer(1,n,audio.sampleRate),d=buf.getChannelData(0);for(let i=0;i<n;i++)d[i]=(Math.random()*2-1)*(1-i/n);const src=audio.createBufferSource(),g=audio.createGain();src.buffer=buf;g.gain.value=vol;src.connect(g);g.connect(master||audio.destination);src.start()}catch(e){}}
function sfx(kind,n=1){if(muted)return;unlockAudio();if(kind==='tap'){tone(220,.035,'square',.06)}else if(kind==='swap'){tone(120,.045,'sawtooth',.07);tone(210,.05,'square',.06,.03)}else if(kind==='bad'){tone(110,.1,'sawtooth',.085,0,-40);noise(.08,.04)}else if(kind==='match'){tone(210+Math.min(n,6)*35,.07,'square',.085);tone(330+Math.min(n,6)*40,.1,'triangle',.075,.035)}else if(kind==='combo'){[220,330,440,660,880].slice(0,Math.min(5,n+1)).forEach((f,i)=>tone(f,.075,i%2?'square':'triangle',.10,i*.035));noise(.06,.045)}else if(kind==='mega'){[110,220,330,440,660,880,1100].forEach((f,i)=>tone(f,.1,i%2?'square':'sawtooth',.11,i*.035));noise(.15,.055)}else if(kind==='extra'){[440,660,880,1320].forEach((f,i)=>tone(f,.12,'square',.12,i*.055));noise(.12,.06)}else if(kind==='level'){[262,330,392,523,659,784].forEach((f,i)=>tone(f,.12,'triangle',.11,i*.06))}else if(kind==='tilt'){tone(85,.22,'sawtooth',.13,0,-35);tone(60,.28,'square',.10,.08,-20);noise(.28,.08)}else if(kind==='end'){funeralSong()}}
function funeralSong(){if(muted)return;unlockAudio();const seq=[196,174.61,164.81,146.83,130.81,123.47,110,98,87.31,82.41,73.42,65.41];seq.forEach((f,i)=>{tone(f,.52,'triangle',.30,i*.38,-f*.08);tone(f/2,.62,'sine',.22,i*.38)});[196,146.83,123.47,98,73.42].forEach((f,i)=>tone(f,.95,'sawtooth',.10,i*.76));setTimeout(()=>{tone(65.41,1.8,'triangle',.36);tone(32.7,2,'sine',.28)},Math.floor(seq.length*.38*1000))}
function vibe(p){if(navigator.vibrate)try{navigator.vibrate(p)}catch(e){}}
function reportLevel(l){const send=()=>{if(window.goatcounter&&typeof window.goatcounter.count==='function'){window.goatcounter.count({path:'riff-level-'+l,title:'HELLXBONE Riff Crush niveau '+l,event:true});return true}return false};if(!send())setTimeout(send,1200);if(l>globalLevel){globalLevel=l;localStorage.setItem('hellx-riff-global-level',String(l));render()}}
async function fetchGlobalLevel(){for(let l=LEVEL_GOALS.length;l>=1;l--){try{const u='https://hellxbone.goatcounter.com/counter/'+encodeURIComponent('/riff-level-'+l)+'.json';const r=await fetch(u,{cache:'no-store'});if(!r.ok)continue;const j=await r.json();const n=Number(String(j.count||'0').replace(/[^0-9]/g,''));if(n>0){globalLevel=Math.max(globalLevel,l);localStorage.setItem('hellx-riff-global-level',String(globalLevel));render();return globalLevel}}catch(e){}}return globalLevel}
function buildShell(){if(q('#hellx-riff-crush'))return;const el=document.createElement('section');el.id='hellx-riff-crush';el.hidden=true;el.setAttribute('aria-label','HELLXBONE Riff Crush');el.innerHTML='<div id="riff-flash" class="riff-flash" aria-hidden="true"></div><div id="riff-event" class="riff-event" aria-live="assertive"></div><div class="riff-wrap"><div class="riff-top"><div><h2 class="riff-title">HELLXBONE RIFF CRUSH</h2><p class="riff-sub">Match-3 metal façon flipper. Fais péter les combos.</p></div><button type="button" class="riff-close" aria-label="Fermer le jeu">✕</button></div><div class="riff-best">🏆 SCORE RECORD <strong id="riff-best">0</strong> &nbsp;•&nbsp; 🌍 NIVEAU MONDIAL <strong id="riff-global-level">1</strong></div><div class="riff-stats"><div class="riff-stat"><b id="riff-score">0</b><span>Score</span></div><div class="riff-stat"><b id="riff-moves">30</b><span>Balles</span></div><div class="riff-stat"><b id="riff-level">1</b><span>Niveau</span></div><div class="riff-stat"><b id="riff-combo">0</b><span>Combo</span></div></div><div class="riff-progress"><div id="riff-progress-bar"></div></div><div id="riff-message" class="riff-message" aria-live="polite">🤘 RIFF !</div><div id="riff-board" class="riff-board" role="grid" aria-label="Grille du jeu"></div><p class="riff-help">4 alignés = bonus • 5+ = MEGA RIFF • Cascades = combos • Certains paliers donnent EXTRA BALL.</p><div class="riff-actions"><button type="button" class="riff-restart">↻ Recommencer</button><button type="button" class="riff-sound">🔊 Son ON</button></div></div>';document.body.appendChild(el);q('.riff-close').addEventListener('click',closeGame);q('.riff-restart').addEventListener('click',()=>{sfx('tap');newGame()});q('.riff-sound').addEventListener('click',toggleSound);const b=q('#riff-board');b.addEventListener('click',cellClick);b.addEventListener('pointerdown',pointerDown);b.addEventListener('pointerup',pointerUp);b.addEventListener('pointercancel',()=>pointerStart=null)}
function toggleSound(){muted=!muted;q('.riff-sound').textContent=muted?'🔇 Son OFF':'🔊 Son ON';if(!muted){unlockAudio();sfx('level')}}
function randIcon(){return ICONS[Math.floor(Math.random()*ICONS.length)]}
function hasAt(r,c,v){return (c>=2&&board[idx(r,c-1)]===v&&board[idx(r,c-2)]===v)||(r>=2&&board[idx(r-1,c)]===v&&board[idx(r-2,c)]===v)}
function fillFresh(){board=new Array(ROWS*COLS);for(let r=0;r<ROWS;r++)for(let c=0;c<COLS;c++){let v;do{v=randIcon()}while(hasAt(r,c,v));board[idx(r,c)]=v}}
function goalForLevel(l){return LEVEL_GOALS[Math.min(l-1,LEVEL_GOALS.length-1)]}
function render(){const b=q('#riff-board');if(!b)return;b.innerHTML=board.map((v,i)=>'<button type="button" class="riff-cell'+(i===selected?' selected':'')+'" data-i="'+i+'" role="gridcell" aria-label="'+v+' case '+(i+1)+'">'+v+'</button>').join('');q('#riff-score').textContent=score;q('#riff-moves').textContent=moves;q('#riff-combo').textContent=combo;q('#riff-level').textContent=level;q('#riff-best').textContent=Math.max(best,score);const gl=q('#riff-global-level');if(gl)gl.textContent=globalLevel;const prev=level===1?0:goalForLevel(level-1),target=goalForLevel(level),pct=Math.max(0,Math.min(100,((score-prev)/(target-prev))*100));q('#riff-progress-bar').style.width=pct+'%';q('.riff-sound').textContent=muted?'🔇 Son OFF':'🔊 Son ON'}
function adjacent(a,b){const [ar,ac]=pos(a),[br,bc]=pos(b);return Math.abs(ar-br)+Math.abs(ac-bc)===1}
function swap(a,b){[board[a],board[b]]=[board[b],board[a]]}
function matches(){const set=new Set();for(let r=0;r<ROWS;r++){let s=0;for(let c=1;c<=COLS;c++){if(c<COLS&&board[idx(r,c)]===board[idx(r,s)])continue;if(c-s>=3)for(let x=s;x<c;x++)set.add(idx(r,x));s=c}}for(let c=0;c<COLS;c++){let s=0;for(let r=1;r<=ROWS;r++){if(r<ROWS&&board[idx(r,c)]===board[idx(s,c)])continue;if(r-s>=3)for(let y=s;y<r;y++)set.add(idx(y,c));s=r}}return [...set]}
function message(t,hot=false){const m=q('#riff-message');if(m){m.textContent=t;m.classList.toggle('hot',hot)}}
function eventFlash(text,type='combo'){const f=q('#riff-flash'),e=q('#riff-event');if(!f||!e)return;f.className='riff-flash '+type;e.className='riff-event show '+type;e.textContent=text;void f.offsetWidth;f.classList.add('go');setTimeout(()=>{e.classList.remove('show');f.classList.remove('go')},700)}
function gravity(){for(let c=0;c<COLS;c++){let write=ROWS-1;for(let r=ROWS-1;r>=0;r--){const v=board[idx(r,c)];if(v!==null){board[idx(write,c)]=v;if(write!==r)board[idx(r,c)]=null;write--}}while(write>=0){board[idx(write,c)]=randIcon();write--}}}
function updateBest(){if(score>best){best=score;localStorage.setItem('hellx-riff-best',String(best))}}
function checkLevel(){let advanced=false;while(level<LEVEL_GOALS.length&&score>=goalForLevel(level)){level++;reportLevel(level);moves+=5;advanced=true;sfx('level');vibe([20,35,20,35,60]);eventFlash('LEVEL '+level+' • +5 BALLES','level');message('⚡ NIVEAU '+level+' — +5 BALLES !',true)}return advanced}
function maybeExtraBall(mLen,chain){const key=Math.floor(score/1800);if((mLen>=5||chain>=3||score>=1800)&&!extraAwarded.has(key)){extraAwarded.add(key);moves+=3;sfx('extra');vibe([30,30,30,30,80]);eventFlash('EXTRA BALL +3','extra');message('🎱 EXTRA BALL — +3 BALLES !',true);return true}return false}
async function resolve(){let chain=0;while(true){const m=matches();if(!m.length)break;chain++;combo=Math.max(combo,chain);render();m.forEach(i=>q('.riff-cell[data-i="'+i+'"]')?.classList.add('match'));if(m.length>=5){sfx('mega');vibe([25,25,45]);eventFlash('MEGA RIFF','mega')}else if(chain>1){sfx('combo',chain);vibe([15,20,20]);eventFlash('COMBO x'+chain,'combo')}else{sfx('match',m.length);vibe(18)}await wait(150);let bonus=0,points=m.length*10*chain*(1+Math.floor((level-1)*.15));if(m.length>=5)bonus=180;else if(m.length===4)bonus=60;score+=points+bonus;updateBest();if(m.length>=5)message('⚡ MEGA RIFF +'+(points+bonus)+' !',true);else if(m.length===4)message('🔥 DOUBLE RIFF +'+(points+bonus)+' !',true);else message(chain>1?'🤘 COMBO x'+chain+'  +'+points:'💀 RIFF +'+points,chain>1);m.forEach(i=>board[i]=null);gravity();render();await wait(95);maybeExtraBall(m.length,chain);checkLevel();render()}return chain}
function registerBadMove(){const now=Date.now();badMoves=now-lastBadAt<5000?badMoves+1:1;lastBadAt=now;if(badMoves>=3){badMoves=0;sfx('tilt');vibe([90,50,120]);eventFlash('TILT !','tilt');message('☠️ TILT ! Calme le flipper…',true);return true}return false}
async function trySwap(a,b){if(busy||moves<=0||!adjacent(a,b))return;busy=true;sfx('swap');swap(a,b);render();const m=matches();if(!m.length){await wait(110);swap(a,b);selected=null;render();sfx('bad');vibe(30);const tilted=registerBadMove();if(!tilted)message('Pas de riff ici…');if(tilted)await wait(650);busy=false;return}badMoves=0;moves--;selected=null;combo=1;await resolve();if(moves<=0){updateBest();message('☠️ FIN DU SET — '+score+' POINTS',true);sfx('end');vibe([40,60,40])}else if(level>=5)message('🔥 MODE CHAOS — NIVEAU '+level+' !',true);busy=false}
function cellClick(e){const btn=e.target.closest('.riff-cell');if(!btn||busy||moves<=0)return;unlockAudio();sfx('tap');const i=Number(btn.dataset.i);if(selected===null){selected=i;render();return}if(selected===i){selected=null;render();return}if(adjacent(selected,i)){const a=selected;trySwap(a,i)}else{selected=i;render()}}
function pointerDown(e){const btn=e.target.closest('.riff-cell');if(!btn)return;unlockAudio();pointerStart={i:Number(btn.dataset.i),x:e.clientX,y:e.clientY}}
function pointerUp(e){if(!pointerStart||busy||moves<=0){pointerStart=null;return}const dx=e.clientX-pointerStart.x,dy=e.clientY-pointerStart.y;if(Math.max(Math.abs(dx),Math.abs(dy))<24){pointerStart=null;return}const [r,c]=pos(pointerStart.i);let nr=r,nc=c;if(Math.abs(dx)>Math.abs(dy))nc+=dx>0?1:-1;else nr+=dy>0?1:-1;if(nr>=0&&nr<ROWS&&nc>=0&&nc<COLS)trySwap(pointerStart.i,idx(nr,nc));pointerStart=null}
function newGame(){score=0;moves=BASE_MOVES;combo=0;level=1;badMoves=0;extraAwarded.clear();selected=null;busy=false;fillFresh();render();reportLevel(1);fetchGlobalLevel();message('🤘 RIFF !');vibe(12)}
function openGame(){buildShell();newGame();const el=q('#hellx-riff-crush');el.hidden=false;document.body.style.overflow='hidden';unlockAudio();setTimeout(()=>sfx('level'),60);message('🔊 SON ACTIF • Fais ton premier riff !');q('.riff-close').focus()}
function closeGame(){const el=q('#hellx-riff-crush');if(el)el.hidden=true;document.body.style.overflow=''}
function armSecret(){const h=document.querySelector('.hellx-header');if(!h)return;let timer=null,startX=0,startY=0;const clear=()=>{if(timer){clearTimeout(timer);timer=null}};h.addEventListener('pointerdown',e=>{unlockAudio();if(e.button!==undefined&&e.button!==0)return;startX=e.clientX;startY=e.clientY;clear();timer=setTimeout(()=>{timer=null;openGame()},5000)});h.addEventListener('pointermove',e=>{if(Math.abs(e.clientX-startX)>18||Math.abs(e.clientY-startY)>18)clear()});['pointerup','pointercancel','pointerleave'].forEach(n=>h.addEventListener(n,clear));h.addEventListener('contextmenu',e=>{if(timer)e.preventDefault()})}
buildShell();armSecret();window.HellRiffCrush={open:openGame,close:closeGame};})();